version: '3.7'

services:
  nginx:
    image: staticfloat/nginx-certbot
    container_name: nginx
    volumes:
      - letsencrypt:/etc/letsencrypt
      - ./docker/prod/nginx/certbot.conf:/etc/nginx/user.conf.d/nginx_template.conf:ro
      - ./docker/prod/nginx/conf.d/proxy.conf:/etc/nginx/user.conf.d/proxy.conf:ro
    ports:
      - 443:443/tcp
      - 80:80/tcp
    environment:
      CERTBOT_EMAIL: oemr.m.aa@mail.ru
      # variable names are space-separated
      ENVSUBST_VARS: APP
      APP: artur.jollymanager.com
  web:
    environment:
      - USE_HTTPS=1

volumes:
  letsencrypt:
